name: GitHell

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Create Abyss Directory
        run: mkdir -p abyss

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit and Push Changes
        run: |
          git config user.name "0x3EF8"
          git config user.email "0x3ef8@gmail.com"

          FILES=("file1.txt" "file2.txt" "file3.txt" "file4.txt" "file5.txt" "file6.txt" "file7.txt" "file8.txt" "file9.txt" "file10.txt")
          current_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          for FILE in "${FILES[@]}"; do
            FILE_PATH="abyss/$FILE"
            
            for ((i=1; i<=2000; i++)); do
              echo "Commit iteration $i for $FILE"

              echo "  ________.__  __     ___ ___         .__  .__   " > "$FILE_PATH"
              echo " /  _____/|__|/  |_  /   |   \   ____ |  | |  |  " >> "$FILE_PATH"
              echo "/   \  ___|  \   __\/    ~    \_/ __ \|  | |  |  " >> "$FILE_PATH"
              echo "\    \_\  \  ||  |  \    Y    /\  ___/|  |_|  |__" >> "$FILE_PATH"
              echo " \______  /__||__|   \___|_  /  \___  >____/____/ " >> "$FILE_PATH"
              echo "        \/                 \/       \/            " >> "$FILE_PATH"
              echo "----------------------------------------------------" >> "$FILE_PATH"
              echo "The abyss grows deeper with each commit." >> "$FILE_PATH"
              echo "----------------------------------------------------" >> "$FILE_PATH"
              commit_id=$(cat /proc/sys/kernel/random/uuid)
              total_commits=$(git rev-list --count HEAD)
              echo "Commit ID: $commit_id" >> "$FILE_PATH"
              echo "Commit: $total_commits" >> "$FILE_PATH"
              echo "Last Execution Time: $current_time" >> "$FILE_PATH"
              echo "----------------------------------------------------" >> "$FILE_PATH"

              git add "$FILE_PATH"
              git commit -S -m "Commit #$i for $FILE - Total commits: $total_commits ðŸŒ‘"
            done
          done

          git push
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
